apiVersion: v1
kind: Service
metadata:
  name: zabbix-mysql
  namespace: zabbix
  labels:
    app: zabbix-mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 30306
  selector:
    app: zabbix-mysql
