- hosts: 127.0.0.1
  tasks:
    - name: "apply Namespace"
      kubernetes.core.k8s:
        src: manifests/namespaces/prometheus-ns.yml
    - name: "apply Prometheus TSDB volume"
      kubernetes.core.k8s:
        src: manifests/volumes/prometheus-pv.yml
    - name: "apply Prometheus deployment"
      kubernetes.core.k8s:
        src: manifests/workloads/prometheus-sts.yml
    - name: "apply Prometheus service"
      kubernetes.core.k8s:
        src: manifests/services/prometheus-svc.yml
