apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server-dep
  namespace: zabbix
  labels:
    app: zabbix-server
spec:
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:7.4.4-alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 10051
          name: zabbix-trapper
        env:
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-db-settings
              key: db-host
        - name: DB_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: zabbix-db-settings
              key: db-port
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-db-creds
              key: zabbix-db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-creds
              key: zabbix-db-pass
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: zabbix-db-settings
              key: db-name
        - name: ZBX_DBTLSCONNECT
          value: "required"
