apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-dep
  namespace: zabbix
  labels:
    app: zabbix-web
spec:
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:7.4.4-alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-db-settings
              key: db-host
        - name: DB_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: zabbix-db-settings
              key: db-port
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-db-creds
              key: zabbix-db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-creds
              key: zabbix-db-pass
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: zabbix-db-settings
              key: db-name
        - name: ZBX_SERVER_NAME
          value: "Zabbix Kubernetes"
        - name: ZBX_SERVER_HOST
          value: zabbix-server
